
using System;

namespace EPiServer.Business.Commerce.Payment.PayEx.Contracts
{
    public interface IPayExPayment
    {
        /// <summary>
        /// The order number of this payment
        /// </summary>
        string OrderNumber { get; set; }

        /// <summary>
        /// The full URL for the page the user will be redirected to after a successful purchase using this payment
        /// </summary>
        string ReturnUrl { get; set; }

        /// <summary>
        /// Merchant product number/reference for this specific product. We recommend that only the characters A-Z and 0-9 are used in this parameter.
        /// </summary>
        string ProductNumber { get; set; }

        /// <summary>
        /// Order reference generated by PayEx
        /// </summary>
        string PayExOrderRef { get; set; }

        /// <summary>
        /// Merchant’s description of the product.
        /// </summary>
        string Description { get; set; }

        /// <summary>
        /// Clients IP-address
        /// </summary>
        string ClientIpAddress { get; set; }

        /// <summary>
        /// ID of the customer
        /// </summary>
        string CustomerId { get; set; }

        /// <summary>
        /// The full URL for the page the user will be redirected to when the Cancel Purchase button is pressed by the user in PayEx.
        /// </summary>
        string CancelUrl { get; set; }

        /// <summary>
        /// The date and time this payment was created
        /// </summary>
        DateTime Created { get; set; }
    }
}
